name: Trigger auto deployment for anarchychess-prod-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/anarchychess-prod-container-AutoDeployTrigger-a0a63642-2f14-4900-8461-cec6b5a49e8c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ANARCHYCHESSPRODCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ANARCHYCHESSPRODCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ANARCHYCHESSPRODCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend/AnarchyChess.Api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ANARCHYCHESSPRODCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANARCHYCHESSPRODCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: anarchychess-prod-container
          resourceGroup: anarchychess-prod-resource
          imageToBuild: slomg/anarchychess-prod-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


